### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by IWasAndrerstajn** [nicholastay/nodesu#10]
TypeError: Cannot read property 'get' of undefined
`const Discord = require('discord.js')
const nodesu = require('nodesu')`

`const api = new nodesu.Client('')
    let u = nodesu.user.get(args.join(" "), nodesu.Mode.osu)`

    let emb = new Discord.RichEmbed()
    .setDescription(`${args}'s Profile`)
    .addField('Username', u.username)
    .addField('Playcount', u.playcount)
    .addField('Ranked Score', u.rankedScore)
    .addField('Accuracy', u.accuracy)
    .addField('PP Rank', u.ppRank)
    .addField('PP', u.ppRaw)
    .addField('SS Plays', u.countRankSS)
    .addField('S Plays', u.countRankS)
    .addField('A Plays', u.countRankA)
    message.channel.send(emb)
`}`

**Comment by nicholastay** [comment]
You seem to be using the wrong variable to call `.get()`. Instead of the static `nodesu` variable that is referencing the library itself, you should be using the `api` variable, as that refers to the instance that is created, initialised with nodesu's components, your API key and potentially other settings.

**Comment by IWasAndrerstajn** [comment]
yeah thats fixed. simple problem didn't even see it. But now its not getting the user's stats, what could be the problem

**Comment by nicholastay** [comment]
I think I see the issue. `nodesu` is a Promise-based library. You seem to be calling the library's functions as if it was *synchronous*. Please read up on `Promise`s as in ES6, and follow this asynchronous flow probably on MDN (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise).

So for example you'd need something like:
`.get(...).then(data => { /* data would be what you need here */ });`

**Comment by IWasAndrerstajn** [comment]
I used the way you said only the accuracy and play count are returned everything else is undefined

**Comment by nicholastay** [comment]
IIRC the osu! API should just return a blank array with no users if there's no matching users, so you can just test for length >0.

**Comment by IWasAndrerstajn** [comment]
Thanks for the help. And nice work with the api wrapper

**Comment by nicholastay** [comment]
Cheers, enjoy the library :)

**Comment by IWasAndrerstajn** [comment]
Sorry for reopening this but for some reason it doesent work anymore. I mean it doesn't get data What could be the problem. Worked untill yesterday
