### ISSUE TITLE
Proper Replay handling

### ISSUE THREAD

**Issue by ThePooN** [nicholastay/nodesu#24]
I'm not exactly sure what defines the exact scope of the library, so I'm just leaving this as an idea.

It would be great maybe to provide better support for replays? Right now, we're only passing the base64-encoded string from the API, we could at least make it a buffer (only if `parseData` is enabled maybe?).

Optionally, we could actually turn the API replay data into an .osr file (see how this is possible with [omkelderman/osu-replay-downloader](https://github.com/omkelderman/osu-replay-downloader)), so users don't have to reinvent the wheel every time, as there's currently no library for that available in npm. That may be a little far from the scope of nodesu though, so we could make it a separate module and link it in the doc as well.

**Comment by nicholastay** [comment]
I feel like to actually generate the `.osr` file may be slightly outside the scope of `nodesu` as you alluded to. I'll probably turn it into a buffer if `parseData` is enabled as you suggested, but other than that, actually turning it into an `.osr` file could probably be left to another module, as `nodesu` is designed to just be an API wrapper.

**Comment by ThePooN** [comment]
Sounds good to me. :+1:

**Comment by nicholastay** [comment]
Implemented this in 80f9286
