### ISSUE TITLE
Add score id

### ISSUE THREAD

**Issue by VINXIS** [nicholastay/nodesu#36]
If possible can u add the ID for a score as well? It's returned in api calls like get_user_best and can be used to link to the score page directly like https://osu.ppy.sh/scores/osu/2220542461 or to a direct replay download like https://osu.ppy.sh/scores/osu/2220542461/download for ex

**Comment by nicholastay** [comment]
This should now be resolved through 67a6c4e

With our structs, we should consider adding helpers to get things such as those urls, e.g. Score.scoreUrl -> takes you to a /scores/osu/ID url for convenience.

Also, I'm not sure if these score IDs will ever get too big such that Node can't handle them (I'm assuming on their server side they're still 64bit ints or the like) - I just remember this happening with the Discord API and their snowflake IDs. We should be okay for now though.
