### ISSUE TITLE
Error: Cannot find module './components/BeatmapsComponent'

### ISSUE THREAD

**Issue by Demon0no** [nicholastay/nodesu#6]
When trying out the library I get the following error. 

> Error: Cannot find module './components/BeatmapsComponent'
>     at Function.Module._resolveFilename (module.js:470:15)
>     at Function.Module._load (module.js:418:25)
>     at Module.require (module.js:498:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (/[CENSORED]/node_modules/nodesu/lib/Client.js:6:27)
>     at Module._compile (module.js:571:32)
>     at Object.Module._extensions..js (module.js:580:10)
>     at Module.load (module.js:488:32)
>     at tryModuleLoad (module.js:447:12)
>     at Function.Module._load (module.js:439:3)

Happens both with the default npm version and with the github npm version.
My node.js version is v4.7.2 and I'm on ubuntu 17.04

Although I don't think that's the problem since it also happens on runkit: https://npm.runkit.com/nodesu

**Comment by nicholastay** [comment]
Simply forgot to rename a file, should be fixed now in v0.6.2! :)
